apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpreE9URXpNakl3SGhjTk1qWXdNVEl6TVRnd01qQXlXaGNOTXpZ>
    server: https://127.71.237.35:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJRmZxMW4rZGlMQmN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelk1TVRreE16SXlNQjRYRFRJMk1ERXlNekU0TURJd01>
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUJibStEOTdiamtZOFJncTVXNk51ak9MYSs3L3U0UWVZN1owYW5QSVdKMUlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFeW1iMUxFRUJ1RVQ4eDdFSWdaUFdCZTlBS1RBeG5nNW1TOXRJOUpjL3BTb0w>


